title: "BOSTON GAMEDEV WEEK"
about: "Get a full week of gamedev goodness here on the bay. Coinciding with PAX East, Boston Gamedev Week is a slate of events focused on developers."

markdown: kramdown
future: true
timezone: America/New_York

url: https://www.gamedev.boston

legal: "Â© Boston Game Dev, all rights reserved."

discord_invite: "https://discord.gg/xRtDPqky"

meetup: "https://www.meetup.com/bostongamedev/"

collections:
  events:
    output: true
    permalink: :collection/:title
  locations:
    output: false
  socials:
    output: false
  links:
    output: false
  badges:
    output: false
  information:
    output: false

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

2025_week_start: 2025-05-05 00:00:00 America/New_York
2025_pax_day_num: 2

2026_week_start: 2026-03-23 00:00:00 America/New_York
2026_pax_day_num: 2